spring.application.name=cosmo42

spring.datasource.url=jdbc:mariadb://localhost:33006/cosmo42
spring.datasource.username=cosmo42
spring.datasource.password=changeme
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migrations

server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=10KB
spring.servlet.multipart.max-file-size=10MB

spring.ai.openai.base-url=http://192.168.50.58:8000/v1
spring.ai.openai.api-key=ON-PREMISE-LLM-FAKE-KEY
spring.ai.openai.embedding.base-url=http://192.168.50.58:8001
spring.ai.openai.embedding.embeddings-path=/embeddings
spring.ai.chat.memory.repository.jdbc.initialize-schema=never

cosmo42.model.llm.name=cyankiwi/gemma-4-26B-A4B-it-AWQ-4bit
cosmo42.model.embedding.name=BAAI/bge-m3
cosmo42.chunking.pool.size=3
cosmo42.fs.storage.path=/tmp/cosmo42
cosmo42.fs.service.implementation=local




logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.docx4j.utils.StaXInputFactoryUtils=ERROR
